"""
app.py — Kalshiyaa Traders CFO Financial Analytics Platform
Run: streamlit run app.py
"""
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from data_cleaning import load_and_clean, monthly_summary, kpi_summary

st.set_page_config(
    page_title="Kalshiyaa Traders — CFO Analytics",
    page_icon="💰",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Dark theme override
st.markdown("""
<style>
  [data-testid="stMetricValue"] { font-size: 1.6rem !important; font-weight: 800 !important; }
  [data-testid="stMetricDelta"] { font-size: 0.9rem !important; }
  .block-container { padding-top: 1.5rem; }
</style>
""", unsafe_allow_html=True)

@st.cache_data
def get_data():
    df = load_and_clean()
    monthly = monthly_summary(df)
    kpis = kpi_summary(df, monthly)
    return df, monthly, kpis

df, monthly, kpis = get_data()

# ── SIDEBAR ──────────────────────────────────────────────
with st.sidebar:
    st.title("💰 CFO Analytics")
    st.caption("Kalshiyaa Traders · Union Bank of India")
    st.divider()
    page = st.radio("Navigation", [
        "📊 Executive Overview",
        "💸 Cash Flow",
        "📈 Income Analysis",
        "📉 Expense Analysis",
        "📋 Transactions",
        "💡 Insights",
    ])
    st.divider()
    # Month filter
    months_list = sorted(df["Month"].unique())
    sel_months = st.multiselect("Filter Months", months_list, default=months_list)
    df_f = df[df["Month"].isin(sel_months)]
    monthly_f = monthly_summary(df_f)
    st.caption(f"Showing {len(df_f):,} of {len(df):,} transactions")
    st.divider()
    st.caption("Generated by Abishek Mohanraj")
    st.caption("Data Analyst & BI Consultant")

COLORS = {"credits":"#10B981","debits":"#EF4444","primary":"#3B82F6",
          "purple":"#8B5CF6","warning":"#F59E0B"}
GRID = dict(color="rgba(255,255,255,0.06)")

def fmt(v): return f"₹{v:,.0f}"
def fmtL(v): return f"₹{v/100000:.1f}L"

# ── PAGE: OVERVIEW ───────────────────────────────────────
if page == "📊 Executive Overview":
    st.title("📊 Executive Overview")
    st.caption("Full-year financial health snapshot · Apr 2025 – Mar 2026")

    c1,c2,c3,c4,c5,c6 = st.columns(6)
    c1.metric("Total Credits",  fmtL(kpis["total_credits"]))
    c2.metric("Total Debits",   fmtL(kpis["total_debits"]))
    c3.metric("Net Cash Flow",  fmtL(kpis["net_cash_flow"]),
              delta=f"{kpis['savings_rate_pct']:.1f}% savings")
    c4.metric("Opening Balance", fmtL(kpis["opening_balance"]))
    c5.metric("Closing Balance", fmtL(kpis["closing_balance"]))
    c6.metric("Health Score", f"{kpis['financial_health_score']}/100")

    st.divider()
    col1, col2 = st.columns([2,1])
    with col1:
        fig = go.Figure()
        fig.add_trace(go.Bar(name="Credits", x=monthly_f["MonthLabel"], y=monthly_f["Credits"],
                             marker_color=COLORS["credits"], text=[fmtL(v) for v in monthly_f["Credits"]], textposition="auto"))
        fig.add_trace(go.Bar(name="Debits",  x=monthly_f["MonthLabel"], y=monthly_f["Debits"],
                             marker_color=COLORS["debits"],  text=[fmtL(v) for v in monthly_f["Debits"]],  textposition="auto"))
        fig.update_layout(barmode="group", title="Monthly Credits vs Debits",
                          template="plotly_dark", height=380, font=dict(family="Segoe UI"))
        st.plotly_chart(fig, use_container_width=True)
    with col2:
        pm = df_f.groupby("Payment_Mode")["Date"].count().reset_index().rename(columns={"Date":"Count"})
        fig2 = px.pie(pm, names="Payment_Mode", values="Count", hole=.55,
                      title="Payment Mode Mix", template="plotly_dark",
                      color_discrete_sequence=px.colors.qualitative.Set2)
        fig2.update_layout(height=380)
        st.plotly_chart(fig2, use_container_width=True)

    bal = df_f.groupby("Date")["Balance"].last().reset_index()
    fig3 = px.area(bal, x="Date", y="Balance", title="Daily Running Balance",
                   template="plotly_dark", color_discrete_sequence=[COLORS["primary"]],
                   labels={"Balance":"Balance (₹)"})
    fig3.update_layout(height=300, font=dict(family="Segoe UI"))
    st.plotly_chart(fig3, use_container_width=True)

# ── PAGE: CASH FLOW ──────────────────────────────────────
elif page == "💸 Cash Flow":
    st.title("💸 Cash Flow Analysis")
    c1,c2,c3,c4 = st.columns(4)
    ncf = monthly_f["NetCashFlow"]
    c1.metric("Avg Monthly Burn", fmtL(kpis["avg_monthly_burn"]))
    c2.metric("Savings Rate", f"{kpis['savings_rate_pct']:.1f}%")
    c3.metric("Liquidity Ratio", f"{kpis['liquidity_ratio']:.2f}x")
    c4.metric("Cash Runway", f"{kpis['runway_months']:.1f} months")
    st.divider()

    colors_wf = [COLORS["credits"] if v>=0 else COLORS["debits"] for v in ncf]
    fig = go.Figure(go.Bar(x=monthly_f["MonthLabel"], y=ncf,
        marker_color=colors_wf, text=[fmtL(v) for v in ncf], textposition="auto", name="Net CF"))
    fig.add_hline(y=0, line_dash="dash", line_color="gray")
    fig.update_layout(title="Monthly Net Cash Flow", template="plotly_dark", height=380,
                      showlegend=False, font=dict(family="Segoe UI"))
    st.plotly_chart(fig, use_container_width=True)

    col1, col2 = st.columns(2)
    with col1:
        sr_colors = [COLORS["credits"] if v>=0 else COLORS["debits"] for v in monthly_f["SavingsRate"]]
        fig2 = go.Figure(go.Bar(x=monthly_f["MonthLabel"], y=monthly_f["SavingsRate"],
            marker_color=sr_colors, text=[f"{v:.1f}%" for v in monthly_f["SavingsRate"]], textposition="auto"))
        fig2.update_layout(title="Monthly Savings Rate %", template="plotly_dark", height=320)
        st.plotly_chart(fig2, use_container_width=True)
    with col2:
        fig3 = go.Figure()
        fig3.add_trace(go.Scatter(x=monthly_f["MonthLabel"], y=monthly_f["CloseBal"],
            mode="lines+markers", fill="tozeroy", line=dict(color=COLORS["purple"]),
            fillcolor="rgba(139,92,246,.15)", marker=dict(size=7)))
        fig3.update_layout(title="Monthly Closing Balance", template="plotly_dark", height=320, showlegend=False)
        st.plotly_chart(fig3, use_container_width=True)

# ── PAGE: INCOME ─────────────────────────────────────────
elif page == "📈 Income Analysis":
    st.title("📈 Income Analysis")
    ti = df_f[df_f["Deposit"]>0].groupby("Party_Name")["Deposit"].sum().sort_values(ascending=False).head(15).reset_index()
    cat_i = df_f[df_f["Deposit"]>0].groupby("Category")["Deposit"].sum().reset_index()
    col1,col2 = st.columns(2)
    with col1:
        fig = px.bar(monthly_f, x="MonthLabel", y="Credits", title="Monthly Inflow",
                     template="plotly_dark", color_discrete_sequence=[COLORS["credits"]])
        st.plotly_chart(fig, use_container_width=True)
    with col2:
        fig2 = px.pie(cat_i, names="Category", values="Deposit", title="Income by Category",
                      template="plotly_dark", hole=.4)
        st.plotly_chart(fig2, use_container_width=True)
    fig3 = px.bar(ti, x="Deposit", y="Party_Name", orientation="h",
                  title="Top 15 Income Sources", template="plotly_dark",
                  color="Deposit", color_continuous_scale="Greens",
                  text=[fmtL(v) for v in ti["Deposit"]])
    fig3.update_layout(yaxis={"autorange":"reversed"}, height=520)
    st.plotly_chart(fig3, use_container_width=True)

# ── PAGE: EXPENSE ────────────────────────────────────────
elif page == "📉 Expense Analysis":
    st.title("📉 Expense Analysis")
    tv = df_f[df_f["Withdrawal"]>0].groupby("Party_Name")["Withdrawal"].sum().sort_values(ascending=False).head(15).reset_index()
    cat_d = df_f[df_f["Withdrawal"]>0].groupby("Category")["Withdrawal"].sum().reset_index()
    col1,col2 = st.columns(2)
    with col1:
        fig = px.bar(monthly_f, x="MonthLabel", y="Debits", title="Monthly Outflow",
                     template="plotly_dark", color_discrete_sequence=[COLORS["debits"]])
        st.plotly_chart(fig, use_container_width=True)
    with col2:
        fig2 = px.pie(cat_d, names="Category", values="Withdrawal", title="Expense by Category",
                      template="plotly_dark", hole=.4, color_discrete_sequence=px.colors.qualitative.Set1)
        st.plotly_chart(fig2, use_container_width=True)
    fig3 = px.bar(tv, x="Withdrawal", y="Party_Name", orientation="h",
                  title="Top 15 Expense Vendors", template="plotly_dark",
                  color="Withdrawal", color_continuous_scale="Reds",
                  text=[fmtL(v) for v in tv["Withdrawal"]])
    fig3.update_layout(yaxis={"autorange":"reversed"}, height=520)
    st.plotly_chart(fig3, use_container_width=True)

# ── PAGE: TRANSACTIONS ───────────────────────────────────
elif page == "📋 Transactions":
    st.title("📋 Transaction Register")
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("🟢 Top 20 Largest Credits")
        big_c = df_f.nlargest(20, "Deposit")[["Date","Party_Name","Deposit","Payment_Mode"]]
        big_c["Date"] = big_c["Date"].dt.strftime("%d %b %Y")
        big_c["Deposit"] = big_c["Deposit"].apply(lambda x: f"₹{x:,.0f}")
        st.dataframe(big_c, use_container_width=True, hide_index=True)
    with col2:
        st.subheader("🔴 Top 20 Largest Debits")
        big_d = df_f.nlargest(20, "Withdrawal")[["Date","Party_Name","Withdrawal","Payment_Mode"]]
        big_d["Date"] = big_d["Date"].dt.strftime("%d %b %Y")
        big_d["Withdrawal"] = big_d["Withdrawal"].apply(lambda x: f"₹{x:,.0f}")
        st.dataframe(big_d, use_container_width=True, hide_index=True)

# ── PAGE: INSIGHTS ───────────────────────────────────────
elif page == "💡 Insights":
    st.title("💡 Executive Insights")
    insights = [
        ("✅ Strength", "#10B981", "Strong Annual Throughput",
         f"₹{kpis['total_credits']/1e7:.2f} Cr total credits demonstrate robust trade activity with diversified counterparties."),
        ("⚠️ Risk", "#F59E0B", "Razor-Thin Savings Rate",
         f"At {kpis['savings_rate_pct']:.1f}% net savings, any large surprise debit risks a cash-flow crisis."),
        ("🔴 Critical", "#EF4444", "Cash Runway < 1 Month",
         f"Current runway is {kpis['runway_months']:.1f} months. A credit line of ₹30-50L is strongly recommended."),
        ("✅ Opportunity", "#10B981", "Digital Revenue Stable",
         "Google India Digital Services contributes ₹40.8L+ — a growing, low-concentration income stream."),
        ("⚠️ Risk", "#F59E0B", "Vendor Concentration",
         "Rajalakshmi Agencies = 28% of total outflows. Diversify supplier base immediately."),
        ("✅ Strength", "#10B981", "Q4 Surplus Recovery",
         "Mar 2026 posted ₹9.74L net surplus — strongest month FY26, positive momentum into FY27."),
        ("⚠️ Pattern", "#F59E0B", "Recurring June & Feb Deficits",
         "Both months consistently run negative. Pre-fund accounts by ₹10L+ 30 days ahead each cycle."),
        ("🔴 Operational", "#EF4444", "Returned Transactions",
         "₹5.44L in 'Insufficient Funds' returns — indicates cash management gaps and incurs bank penalties."),
        ("✅ Opportunity", "#10B981", "Real Estate Receipts",
         "₹10.3L+ from real estate builders (Athulayam, Prashant Homes, Vettri Estates) — high-value clients."),
        ("⚠️ Recommendation", "#F59E0B", "Establish OD Facility",
         "Negotiate a ₹30-50L overdraft with Union Bank of India to buffer monthly cash flow swings."),
        ("✅ Strength", "#10B981", "NEFT Dominates (42%)",
         "NEFT is the primary channel — traceable, low-risk, and efficient. Maintain and expand adoption."),
        ("⚠️ Recommendation", "#F59E0B", "Weekly Cash Flow Reviews",
         "Implement weekly CFO cash forecasts 4 weeks ahead. Current monthly-level visibility is insufficient."),
    ]
    for i in range(0, len(insights), 3):
        cols = st.columns(3)
        for j, (tag, color, title, body) in enumerate(insights[i:i+3]):
            cols[j].markdown(f"""
            <div style="background:#1E293B;border-radius:12px;padding:18px;
                border-left:4px solid {color};margin-bottom:8px">
              <div style="font-size:11px;color:#94A3B8;text-transform:uppercase;
                  letter-spacing:.7px;margin-bottom:6px">{tag}</div>
              <div style="font-size:15px;font-weight:700;margin-bottom:8px">{title}</div>
              <div style="font-size:13px;color:#94A3B8;line-height:1.6">{body}</div>
            </div>""", unsafe_allow_html=True)
